### ISSUE TITLE
Main Login und Newsletter Option

### ISSUE THREAD

**Issue by rnt-ash** [RNT-Forest/CORE#10]
Ein Login soll zum Mainuser gemacht werden können. Zu jedem Customer muss ein Mainuser existieren.
Bei jedem Login soll der Newsletter Aus- oder Abgewählt werden können.

**Comment by rnt-oak** [comment]
Chrome:
![image](https://cloud.githubusercontent.com/assets/8237230/23215608/4bcd390e-f913-11e6-99c9-e13c2a09288f.png)

**Comment by rnt-oak** [comment]
Problem behoben..
