### ISSUE TITLE
Autocomplete einbauen

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/CORE#11]
Basis: https://github.com/bassjobsen/Bootstrap-3-Typeahead
Vorerst nur bei der Auswahl von Kunden in z.B. VirtualServers oder PhysicalServers

**Comment by rnt-oak** [comment]
Noch einer: https://silviomoreto.github.io/bootstrap-select/

**Comment by rnt-ash** [comment]
Ist im Moment nur beim Partners Modul eingebaut. Müsste bei allen anderen Modulen auch noch hinzugefügt werden.
