### ISSUE TITLE
Pending entfernen im GUI (Admin)

### ISSUE THREAD

**Issue by rnt-maple** [RNT-Forest/CORE#28]
Für den Administrator (admin=1) soll es möglich sein auf einfache Weise im GUI Objekte, welche sich im gelockten Pending-Zustand befinden zu entpendieren.

Varianten:
1. Pending im View des entsprechenden Models darstellen/entfernen
2. Pendierte Objekte im Admin-Dashboard auflisten (Problem, welche Models können alle Pending haben?)

**Comment by rnt-oak** [comment]
Vorschlag: Pending-Entfernen Knopf im Slide Header einbauen. JSON Aarray wird komplett gelöscht.
Dieser Knopf kann nur mit der Berechtigung administration:pending:* verwendet werden. (Also Admins und Employees)
Entsprechende Berechtigung wurde vorbereitet.

**Comment by rnt-oak** [comment]
Pending entfernen funktioniert als employee nicht. vermutlich Probleme mit Permission

**Comment by rnt-ash** [comment]
Bug wurde behoben, war ein Schreibfehler in der permissionbase.
