### ISSUE TITLE
Edit Formular überarbeiten

### ISSUE THREAD

**Issue by rnt-ash** [RNT-Forest/CORE#5]
Das Formular um Logins zu erstellen und bearbeiten soll optisch überarbeitet werden.

**Comment by rnt-oak** [comment]
Bootstrap Umbruch ist etwas "unglücklich" und Bereiche bleiben auf der rechten Seite frei.
Umbruch ev. in drei Stufen ? (Handy, Tablet, PC ?)
Vorname mit Nachname austauschen. (zuerst Vorname, dann Nachname)

**Comment by rnt-oak** [comment]
Speichern eines neuen Logins funktioniert nicht. Formular kommt ohne speichern und ohne Meldung zurück:
![image](https://cloud.githubusercontent.com/assets/8237230/23250601/20161988-f9aa-11e6-8bf4-e7817f3f7a7a.png)

**Comment by rnt-ash** [comment]
Layout entsprechend nach dem Issue #14 angepasst.

**Comment by rnt-ash** [comment]
@rnt-oak eigentliches Edit Formular wurde überarbeitet. Bootstrap Ansicht/Layout wird aufgrund vom Issue #14 angepasst. Kann dieser Issue somit abgeschlossen werden?

**Comment by rnt-oak** [comment]
Auf der rechten Seite immer noch grosser Leerraum.
