### ISSUE TITLE
TableSlide: Add Button nur wenn Berechtigung vorhanden ist

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/CORE#55]
Konkret aktuelle in Physical- und Virtual Server. Problem sollte aber bei allen Anwendungen sein.
Hosted Websites, Domänen und Domänen Kontakte auch beachten.

**Comment by rnt-ash** [comment]
Der New button könnte man bei Tabledata Modulen evtl. auch in den Header nehmen (neben der row Auswahl), damit es überall, im Slide- und Tabledata, gleich ist.
