### ISSUE TITLE
Logins Passwort ohne Bestätigung, dafür mit Wizard

### ISSUE THREAD

**Issue by rnt-oak** [RNT-Forest/CORE#64]
![pwd](https://user-images.githubusercontent.com/8237230/28423554-a0ed5a5a-6d6b-11e7-9857-07444d225d28.jpg)

Solange der Admin ein Passwort ändern möchte, muss er dieses nicht doppelt eingeben. Der Passwort Generator ist somit auch erwünscht.
Will ein User sein eigenes Passwort ändern, so muss er das Passwort doppelt eingeben. Ein Wizard wird nicht benötigt, denke ich...

**Comment by rnt-ash** [comment]
Wurde erledigt.
