### ISSUE TITLE
PDF für Logins

### ISSUE THREAD

**Issue by rnt-ash** [RNT-Forest/CORE#8]
Wenn ein neuer Benutzer erstellt wird oder von einem Login das Passwort zurückgesetzt wird, soll ein PDF mit den Login Daten inklusive Passwort erstellt werden, welches an den Kunden verschickt werden kann.
PDF wird im cache Ordner zwischen gespeichert und soll nach ein paar Minuten durch einen Cronjob gelöscht werden.

**Comment by rnt-oak** [comment]
Welche permissions?
![image](https://cloud.githubusercontent.com/assets/8237230/23250463/955a7c08-f9a9-11e6-872f-24e4314bb968.png)

**Comment by rnt-ash** [comment]
PDF wird nun in allen Browsern korrekt angezeigt und hat beim Herunterladen einen sinnvollen Namen. e595dd5b1bffeb08e5e0ac05ee25bf35b6b485f1
